export enum Capability {
  ORGANIZATION_READ = 'organization:read',
  ORGANIZATION_UPDATE = 'organization:update',
  ORGANIZATION_DELETE = 'organization:delete',
  ORGANIZATION_LEAVE = 'organization:leave',
  MEMBERSHIP_READ = 'membership:read',
  MEMBERSHIP_CHANGE_ROLE = 'membership:change-role',
  MEMBERSHIP_REMOVE = 'membership:remove',
  INVITATION_READ = 'invitation:read',
  INVITATION_CREATE = 'invitation:create',
  INVITATION_RESEND = 'invitation:resend',
  INVITATION_REVOKE = 'invitation:revoke',
  OWNERSHIP_TRANSFER = 'ownership:transfer',
  BILLING_READ = 'billing:read',
  BILLING_MANAGE = 'billing:manage',
  NOTIFICATION_READ = 'notification:read',
  NOTIFICATION_MANAGE = 'notification:manage',
  FILE_READ = 'file:read',
  FILE_UPLOAD = 'file:upload',
  FILE_DELETE = 'file:delete',
}
