allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  argon2: true
  esbuild: true
  prisma: true
  unrs-resolver: true

overrides:
  '@nestjs/swagger>js-yaml': 5.2.3
  deepmerge-ts: 8.0.1
  fast-uri: 3.1.6
  multer: 2.3.0
  mysql2: 3.23.1
  qs: 6.16.0
